[[headers]]
  for = "/"
  [headers.values]
    Netlify-Vary = "query=githubStars|posts|readingList,header=Sec-CH-UA-Mobile|User-Agent,cookie=hideWipBanner"

[[headers]]
  for = "/index-mobile"
  [headers.values]
    X-Robots-Tag = "noindex"

[[redirects]]
  from = "/proxy/cloudinary/*"
  to = "https://res.cloudinary.com/wolstenh/:splat"
  status = 200

[[redirects]]
  from = "/proxy/jsdelivr/*"
  to = "https://cdn.jsdelivr.net/:splat"
  status = 200

[[redirects]]
  from = "/proxy/gstatic/*"
  to = "https://t2.gstatic.com/:splat"
  status = 200

[[plugins]]
  package = "netlify-plugin-subfont"
  [plugins.inputs]
    entryPoints = [
      "*.html",
      "**/*.html"
    ]